name: Deploy to dev

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Dev
    steps: 
    - name: SSH into dev and execute deploy.sh
      uses: appleboy/ssh-action@v1.0.3
      with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into

          script: |
            if [ -d "pdf-api" ]; then
              cd ~/pdf-api
              git fetch
              git checkout dev
              git pull
            else
              git clone https://github.com/Research-IT-Swiss-TPH/pdf-api.git
              cd ~/pdf-api
              git fetch
              git checkout dev
              git pull
            fi

            docker compose -f compose.dev.yml up --remove-orphans 
